import {
  GroupMember,
  HubzzEvent,
  HubzzGroupProfile,
  HubzzNotification,
  HubzzStage,
  HubzzStub,
  HubzzTicket,
  DropInSession,
  StreamQueue,
} from './hubzz-api';

export const mockEvent: HubzzEvent = {
  id: 'event-123',
  name: 'Hubzz Connect Live',
  description: 'A preview event showcasing Hubzz spatial venues.',
  startTime: new Date(Date.now() + 1000 * 60 * 60).toISOString(),
  endTime: new Date(Date.now() + 1000 * 60 * 60 * 4).toISOString(),
  groupId: 'group-1',
  zoneId: 'zone-1',
  venueCoordinates: { x: 10, y: 0, z: -4 },
  ticketPrice: 12,
  recordingUrl: undefined,
};

export const mockStages: HubzzStage[] = [
  {
    id: 'stage-a',
    name: 'Main Stage',
    venueModuleId: 'venue-a',
    zoneId: 'zone-1',
    streamType: 'external',
    externalStreamUrl: 'https://youtube.com/embed/mock',
    deepLink: 'https://app.hubzz.com/join?zone=zone-1&venue=venue-a',
    venueCoordinates: { x: 10, y: 0, z: -4 },
    priority: 1,
  },
  {
    id: 'stage-b',
    name: 'Backstage',
    venueModuleId: 'venue-b',
    zoneId: 'zone-1',
    streamType: 'spatial',
    externalStreamUrl: null,
    deepLink: 'https://app.hubzz.com/join?zone=zone-1&venue=venue-b',
    venueCoordinates: { x: 12, y: 0, z: -2 },
    priority: 2,
  },
];

export const mockGroupMembers: GroupMember[] = [
  { id: 'user-1', username: 'Avery Host', avatarUrl: undefined, role: 'owner' },
  { id: 'user-2', username: 'Blair Moderator', avatarUrl: undefined, role: 'admin' },
  { id: 'user-3', username: 'Casey Speaker', avatarUrl: undefined, role: 'member' },
];

export const mockStreamQueue: StreamQueue = {
  eventId: 'event-123',
  activeStreamIndex: 0,
  streams: [
    {
      platform: 'youtube',
      channelId: 'hubzz',
      embedUrl: 'https://youtube.com/embed/mock',
      priority: 1,
    },
    {
      platform: 'twitch',
      channelId: 'hubzz-live',
      embedUrl: 'https://player.twitch.tv/?channel=hubzz-live&parent=localhost',
      priority: 2,
    },
  ],
};

export const mockDropInSession: DropInSession = {
  id: 'dropin-1',
  locationLabel: 'Hubzz rooftop',
  roomName: 'Main Stage Backstage',
  participants: [
    {
      id: 'p1',
      name: 'Wendy',
      role: 'Host',
      isHost: true,
      isMuted: false,
      isSpeaking: true,
    },
    {
      id: 'p2',
      name: 'Myra',
      role: 'Moderator',
      isMuted: false,
      isSpeaking: false,
    },
    {
      id: 'p3',
      name: 'Dimitri',
      role: 'Speaker',
      isMuted: true,
      isSpeaking: false,
    },
    {
      id: 'p4',
      name: 'Alex',
      role: 'Guest',
      isMuted: true,
      isSpeaking: false,
    },
  ],
};

const baseJoinUrl = 'https://app.hubzz.com/join';

export const mockTickets: HubzzTicket[] = [
  {
    id: 'ticket-001',
    eventId: mockEvent.id,
    eventName: 'A Moment to remember',
    venueName: 'Beta Lounge',
    hostName: 'HubzzHQ',
    zoneId: 'zone-1',
    venueModuleId: 'venue-a',
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 27).toISOString(),
    canJoinAt: new Date(Date.now() + 1000 * 60 * 60 * 23).toISOString(),
    issuedAt: new Date().toISOString(),
    ticketNumber: '00001/03123',
    status: 'upcoming',
    deepLink: `${baseJoinUrl}?zone=zone-1&venue=venue-a`,
    isCurrent: true,
  },
  {
    id: 'ticket-002',
    eventId: 'event-456',
    eventName: 'Creators Collective',
    venueName: 'Alpha Dome',
    hostName: 'Hubzz Creators',
    zoneId: 'zone-2',
    venueModuleId: 'venue-b',
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 51).toISOString(),
    issuedAt: new Date().toISOString(),
    ticketNumber: '00002/03123',
    status: 'upcoming',
    deepLink: `${baseJoinUrl}?zone=zone-2&venue=venue-b`,
  },
  {
    id: 'ticket-003',
    eventId: 'event-789',
    eventName: 'A Moment to remember',
    venueName: 'Beta Lounge',
    hostName: 'HubzzHQ',
    zoneId: 'zone-3',
    venueModuleId: 'venue-c',
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 45).toISOString(),
    issuedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    ticketNumber: '00003/03123',
    status: 'stub',
    deepLink: `${baseJoinUrl}?zone=zone-3&venue=venue-c`,
    stubId: 'stub-003',
  },
];

export const mockStubs: HubzzStub[] = [
  {
    id: 'stub-003',
    ticketId: 'ticket-003',
    ticketNumber: '00003/03123',
    eventName: 'A Moment to remember',
    description:
      'A full-venue takeover with interactive art, live music, and behind-the-scenes creator moments captured for replay.',
    venueName: 'Beta Lounge',
    venueImageUrl: 'https://placehold.co/720x360/0b1021/ffffff?text=Beta+Lounge+replay+snapshot',
    hostName: 'HubzzHQ',
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 45).toISOString(),
    zoneId: 'zone-3',
    venueModuleId: 'venue-c',
    replayUrl: 'https://app.hubzz.com/replay/stub-003',
    hostedBy: [
      { id: 'group-1', name: 'Group', role: 'Organizers' },
      { id: 'user-1', name: 'Cody', role: 'Host' },
      { id: 'user-2', name: 'Kyle', role: 'Host' },
      { id: 'user-3', name: 'Ronald', role: 'Moderator' },
      { id: 'user-4', name: 'John', role: 'Moderator' },
    ],
    guests: [
      { id: 'guest-1', name: 'Soham', durationMinutes: 60, attendeeNumber: 1 },
      { id: 'guest-2', name: 'Leslie', durationMinutes: 59, attendeeNumber: 2 },
      { id: 'guest-3', name: 'Arlene', durationMinutes: 58, attendeeNumber: 3 },
      { id: 'guest-4', name: 'Kristin', durationMinutes: 57, attendeeNumber: 4 },
      { id: 'guest-5', name: 'Aubrey', durationMinutes: 54, attendeeNumber: 5 },
      { id: 'guest-6', name: 'Ronald', durationMinutes: 53, attendeeNumber: 6 },
      { id: 'guest-7', name: 'Courtney', durationMinutes: 52, attendeeNumber: 7 },
      { id: 'guest-8', name: 'Mitchell', durationMinutes: 50, attendeeNumber: 8 },
      { id: 'guest-9', name: 'Shane', durationMinutes: 49, attendeeNumber: 9 },
      { id: 'guest-10', name: 'Cameron', durationMinutes: 48, attendeeNumber: 10 },
    ],
    guestCount: 1324,
    stubCode: 'stub-003',
  },
];

export const mockGroupProfile: HubzzGroupProfile = {
  id: 'group-1',
  name: 'RetrosDoges',
  description: 'This group is like lorem ipsum dolor sit amet is professional dummy text',
  category: 'Community',
  coverImageUrl: 'https://placehold.co/1440x720/161b2f/ffffff?text=Group+cover',
  avatarUrl: 'https://placehold.co/160x160/9246ff/ffffff?text=RD',
  followerLabel: 'Followed',
  isFollowed: true,
  stubCount: 12,
  badgeLabel: 'Community',
  events: [
    {
      id: 'event-weekly-24',
      name: 'Weekly Meetup: 24',
      hostName: 'Path',
      startTime: '2024-01-19T21:00:00.000Z',
      endTime: '2024-01-20T00:00:00.000Z',
      status: 'upcoming',
      attendeeCount: 24,
      isFree: true,
      rsvpLabel: 'RSVP',
      ctaLabel: 'RSVP | FREE',
      ctaHref: '/event/event-weekly-24',
      imageUrl: 'https://placehold.co/720x360/0b1021/ffffff?text=Weekly+Meetup+24',
    },
    {
      id: 'event-weekly-25',
      name: 'Weekly Meetup: 25',
      hostName: 'Path',
      startTime: '2024-01-25T21:00:00.000Z',
      endTime: '2024-01-26T00:00:00.000Z',
      status: 'upcoming',
      attendeeCount: 18,
      isFree: true,
      rsvpLabel: 'RSVP',
      ctaLabel: 'RSVP | FREE',
      ctaHref: '/event/event-weekly-25',
      imageUrl: 'https://placehold.co/720x360/0b1021/ffffff?text=Weekly+Meetup+25',
    },
    {
      id: 'event-weekly-26',
      name: 'Weekly Meetup: 26',
      hostName: 'Path',
      startTime: '2024-02-02T21:00:00.000Z',
      endTime: '2024-02-03T00:00:00.000Z',
      status: 'upcoming',
      attendeeCount: 12,
      isFree: true,
      rsvpLabel: 'RSVP',
      ctaLabel: 'RSVP | FREE',
      ctaHref: '/event/event-weekly-26',
      imageUrl: 'https://placehold.co/720x360/0b1021/ffffff?text=Weekly+Meetup+26',
    },
  ],
  merch: [
    {
      id: 'merch-1',
      name: 'Sofa xp 1',
      subtitle: '1 / 200',
      priceHbc: 1234,
      stubCost: 3,
      requiredStubs: 5,
      ownedStubs: 12,
      imageUrl: 'https://placehold.co/640x360/1a2034/ffffff?text=Sofa+xp1',
      unlockNote: 'Unlocks when you acquire 5 or more event stubs from HubzzHQ',
    },
    {
      id: 'merch-2',
      name: 'Sofa xp 2',
      subtitle: '1 / 200',
      priceHbc: 1234,
      stubCost: 3,
      requiredStubs: 5,
      ownedStubs: 12,
      imageUrl: 'https://placehold.co/640x360/1a2034/ffffff?text=Sofa+xp2',
      unlockNote: 'Unlocks when you acquire 5 or more event stubs from HubzzHQ',
    },
  ],
  members: mockGroupMembers,
};

export const mockNotifications: HubzzNotification[] = [
  {
    id: 'notif-1',
    type: 'event',
    title: 'Hubzz HQ created a new event',
    message: 'A Moment to remember · Starts in 1d 3h',
    ctaLabel: 'View details',
    ctaHref: '/event/event-123',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-2',
    type: 'friend-request',
    title: 'Liam sent you a friend request',
    message: 'Tap to view profile or accept/decline the request.',
    ctaLabel: 'View profile',
    ctaHref: '/profile/liam',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-3',
    type: 'friend-accepted',
    title: 'Nia accepted your friend request',
    message: 'You can now invite them to events and stages.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-4',
    type: 'system',
    title: 'Event starting soon',
    message: 'Creators Collective begins in 15 minutes. Join from your ticket.',
    ctaLabel: 'Open tickets',
    ctaHref: '/tickets',
    createdAt: new Date().toISOString(),
  },
];
